# Generated by Django 5.0.2 on 2024-02-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_group_members_groupmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
