# Generated by Django 5.0.2 on 2024-02-17 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_group_group_name_remove_group_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='member',
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='name',
            field=models.CharField(max_length=100, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=255, null='False'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='users.group'),
        ),
    ]
