# Generated by Django 5.0.2 on 2024-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_groupmembers_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='share',
            field=models.IntegerField(default=0, null='False'),
            preserve_default='False',
        ),
    ]
