# Generated by Django 5.0.2 on 2024-02-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_group_total_amount_alter_groupmembers_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=300, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='date',
            field=models.CharField(max_length=10, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, null='False'),
        ),
    ]
