# Generated by Django 5.0.2 on 2024-02-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_groupmembers_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null='False')),
                ('date', models.CharField(max_length=10, null='False')),
                ('amount', models.FloatField(null='False')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='date',
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='description',
        ),
    ]
