# Generated by Django 5.0.2 on 2024-02-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_expensetable_remove_groupmembers_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetable',
            name='group',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.group'),
            preserve_default='False',
        ),
    ]
