# Generated by Django 5.0.2 on 2024-02-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_expensetable_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetable',
            name='editor',
        ),
    ]
