# Generated by Django 5.0.2 on 2024-02-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_expensetable_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='membersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null='False')),
                ('mail_id', models.CharField(max_length=100, null='False')),
            ],
        ),
    ]
