# Generated by Django 5.0.2 on 2024-02-20 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_memberstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='name',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='users.memberstable'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='share',
            field=models.FloatField(default=0),
        ),
    ]
