# Generated by Django 5.0.2 on 2024-02-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_groupmembers_name_alter_groupmembers_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='total_amount',
            field=models.FloatField(default=0, null='False'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='share',
            field=models.FloatField(default=0, null='False'),
        ),
    ]
