# Generated by Django 5.0.2 on 2024-02-20 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_group_total_amount_alter_groupmembers_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetable',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expensetable',
            name='date',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='expensetable',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='expensetable',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='users.group'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.memberstable'),
        ),
        migrations.AlterField(
            model_name='memberstable',
            name='mail_id',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='memberstable',
            name='user_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
