# Generated by Django 5.0.2 on 2024-02-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_expensetable_amount_alter_expensetable_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberstable',
            name='mail_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
